import type {
  HuttonCalendarEvent,
  HuttonClient,
  HuttonInboxMessage,
  HuttonJob,
  HuttonPart,
  HuttonPartRequest,
  HuttonServiceDataset,
  HuttonSupplier,
  HuttonTechnician,
  HuttonTransportTask,
  HuttonVehicle,
  HuttonWhatsAppUpdate,
} from "@/lib/hutton-service-types";

export const huttonClients: HuttonClient[] = [
  { id: "CL-001", name: "Sarah Daniels", phone: "082 443 1902", email: "sarah.daniels@clientmail.co.za", preferredContact: "WhatsApp", tags: ["Corporate account", "Needs shuttle"] },
  { id: "CL-002", name: "Musa Khumalo", phone: "071 228 4411", email: "musa.khumalo@email.co.za", preferredContact: "Phone", tags: ["Fleet vehicle", "Approval by manager"] },
  { id: "CL-003", name: "Lynette Fourie", phone: "083 770 9254", email: "lynette.fourie@email.co.za", preferredContact: "WhatsApp", tags: ["Repeat client"] },
  { id: "CL-004", name: "Ahmed Patel", phone: "072 618 4500", email: "ahmed.patel@email.co.za", preferredContact: "WhatsApp", tags: ["Urgent turnaround"] },
  { id: "CL-005", name: "Nomsa Dlamini", phone: "084 511 3782", email: "nomsa.dlamini@email.co.za", preferredContact: "Email", tags: ["Warranty history"] },
  { id: "CL-006", name: "Brandon Louw", phone: "079 998 4422", email: "brandon.louw@email.co.za", preferredContact: "WhatsApp", tags: ["Waiting for approval"] },
  { id: "CL-007", name: "Jason Naidoo", phone: "082 650 1184", email: "jason.naidoo@email.co.za", preferredContact: "WhatsApp", tags: ["New booking lead"] },
  { id: "CL-008", name: "Chantel Meyer", phone: "083 332 9914", email: "chantel.meyer@email.co.za", preferredContact: "WhatsApp", tags: ["Needs follow-up"] },
  { id: "CL-009", name: "Sibusiso Mokoena", phone: "071 904 7782", email: "sibusiso.mokoena@email.co.za", preferredContact: "WhatsApp", tags: ["Transport request"] },
  { id: "CL-010", name: "Priya Govender", phone: "084 219 6670", email: "priya.govender@email.co.za", preferredContact: "WhatsApp", tags: ["Schedule conflict"] },
  { id: "CL-011", name: "Megan Jacobs", phone: "082 119 3408", email: "megan.jacobs@email.co.za", preferredContact: "WhatsApp", tags: ["Needs human review"] },
];

export const huttonVehicles: HuttonVehicle[] = [
  { id: "VH-001", clientId: "CL-001", registration: "CA 598-214", make: "Toyota", model: "Fortuner 2.8 GD-6", year: 2022, color: "Pearl White", vin: "AHTBA3FS109332184", mileageKm: 68420, engine: "2.8 Diesel Auto", lastServiceDate: "2026-01-18" },
  { id: "VH-002", clientId: "CL-002", registration: "CY 883-771", make: "Ford", model: "Ranger 2.0 Bi-Turbo XLT", year: 2021, color: "Meteor Grey", vin: "MNAA6KF80MW341222", mileageKm: 112305, engine: "2.0 Diesel Auto", lastServiceDate: "2025-12-02" },
  { id: "VH-003", clientId: "CL-003", registration: "CJ 224-908", make: "Volkswagen", model: "Polo 1.0 TSI Life", year: 2023, color: "Reflex Silver", vin: "WVWBH6AW0PU053812", mileageKm: 24140, engine: "1.0 Petrol DSG", lastServiceDate: "2026-02-11" },
  { id: "VH-004", clientId: "CL-004", registration: "CF 110-335", make: "BMW", model: "320d M Sport", year: 2020, color: "Black Sapphire", vin: "WBA5R52020FH11903", mileageKm: 89540, engine: "2.0 Diesel Auto", lastServiceDate: "2025-11-19" },
  { id: "VH-005", clientId: "CL-005", registration: "CAA 443-10", make: "Hyundai", model: "Tucson 2.0 Executive", year: 2022, color: "Amazon Grey", vin: "TMAJE81BAPJ781004", mileageKm: 53310, engine: "2.0 Petrol Auto", lastServiceDate: "2026-03-01" },
  { id: "VH-006", clientId: "CL-006", registration: "CAW 905-77", make: "Mercedes-Benz", model: "Vito 116 CDI Tourer", year: 2021, color: "Arctic White", vin: "WDF44770313821098", mileageKm: 128900, engine: "2.0 Diesel Auto", lastServiceDate: "2026-01-28" },
];

export const huttonTechnicians: HuttonTechnician[] = [
  { id: "TECH-001", name: "Sipho Mthembu", role: "Senior Technician", bay: "Bay 1", workload: 3, status: "Active", specialties: ["Major service", "Diagnostics", "Quality check"] },
  { id: "TECH-002", name: "Mia Kleyn", role: "Diagnostic Technician", bay: "Bay 3", workload: 2, status: "Active", specialties: ["Electrical", "Fault tracing", "Warranty work"] },
  { id: "TECH-003", name: "Jaco Louw", role: "Workshop Technician", bay: "Bay 5", workload: 2, status: "Available", specialties: ["Brakes", "Suspension", "Service kits"] },
  { id: "TECH-004", name: "Aphiwe Ndlovu", role: "Apprentice Technician", bay: "Bay 2", workload: 1, status: "Break", specialties: ["Vehicle prep", "Road test support"] },
];

export const huttonSuppliers: HuttonSupplier[] = [
  { id: "SUP-001", name: "Masterparts Bellville", contact: "Ruan Botha", phone: "021 948 1120", email: "ruan.botha@masterparts.co.za", sla: "Same day before 15:00", rating: 4.7, tags: ["Fast moving", "OEM alternatives"] },
  { id: "SUP-002", name: "Toyota Parts Cape Town", contact: "Dealer Parts Desk", phone: "021 530 8800", email: "parts.capetown@toyota.co.za", sla: "24 hours", rating: 4.5, tags: ["OEM", "Fortuner", "Hilux"] },
  { id: "SUP-003", name: "German Auto Spares", contact: "Nadia Jacobs", phone: "021 913 4412", email: "nadia@germanautospares.co.za", sla: "24 to 48 hours", rating: 4.6, tags: ["BMW", "VW", "Mercedes"] },
];

export const huttonParts: HuttonPart[] = [
  { id: "PART-001", category: "Braking", sourceType: "OEM", partNumber: "04465-YZZR7", alternatePartNumber: "DBA-FTN-4421", name: "Front brake pad set", vehicleCompatibility: ["Toyota Fortuner 2.8 GD-6", "Toyota Hilux 2.8 GD-6"], supplierId: "SUP-002", supplierSku: "TY-BRK-4421", unitPrice: 1480, retailPrice: 1895, stockOnHand: 2, reorderLevel: 4, tags: ["Brake", "OEM", "Service"], notes: "Best fit for low brake squeal repeat jobs.", lastUsedDate: "2026-04-22" },
  { id: "PART-002", category: "Service kit", sourceType: "Aftermarket", partNumber: "HU-711/51X", alternatePartNumber: "RNG-OF-200BT", name: "Oil filter cartridge", vehicleCompatibility: ["Ford Ranger 2.0 Bi-Turbo", "VW Polo 1.0 TSI"], supplierId: "SUP-001", supplierSku: "MP-OIL-719", unitPrice: 188, retailPrice: 320, stockOnHand: 16, reorderLevel: 10, tags: ["Filter", "Routine service"], notes: "Used on high-volume service bookings.", lastUsedDate: "2026-04-21" },
  { id: "PART-003", category: "Diagnostics", sourceType: "OEM", partNumber: "A0009053103", alternatePartNumber: "MB-NOX-116", name: "NOx sensor", vehicleCompatibility: ["Mercedes-Benz Vito 116 CDI"], supplierId: "SUP-003", supplierSku: "GA-MB-3103", unitPrice: 3920, retailPrice: 4680, stockOnHand: 0, reorderLevel: 1, tags: ["Sensor", "Mercedes", "Diagnostics"], notes: "Often needs coding after fitment.", lastUsedDate: "2026-04-10" },
  { id: "PART-004", category: "Consumables", sourceType: "Aftermarket", partNumber: "8V0-615-301B", alternatePartNumber: "BFK-320D-VW", name: "Brake fluid service kit", vehicleCompatibility: ["BMW 320d", "VW Polo 1.0 TSI"], supplierId: "SUP-003", supplierSku: "GA-BRK-118", unitPrice: 640, retailPrice: 890, stockOnHand: 6, reorderLevel: 3, tags: ["Fluid", "Consumable", "Brake"], notes: "Bundle with road test and reset procedure.", lastUsedDate: "2026-04-19" },
  { id: "PART-005", category: "Service kit", sourceType: "Aftermarket", partNumber: "28113-D3500", alternatePartNumber: "HY-AF-TUC20", name: "Air filter element", vehicleCompatibility: ["Hyundai Tucson 2.0 Executive"], supplierId: "SUP-001", supplierSku: "MP-HY-510", unitPrice: 240, retailPrice: 360, stockOnHand: 3, reorderLevel: 4, tags: ["Filter", "Service", "Hyundai"], notes: "Keep linked to annual service campaign.", lastUsedDate: "2026-04-22" },
  { id: "PART-006", category: "Retail extra", sourceType: "Aftermarket", partNumber: "T6A-998-231", alternatePartNumber: "WIP-FTN-RNG", name: "Wiper blade pair", vehicleCompatibility: ["Ford Ranger 2.0 Bi-Turbo", "Toyota Fortuner 2.8 GD-6"], supplierId: "SUP-001", supplierSku: "MP-WIP-302", unitPrice: 285, retailPrice: 420, stockOnHand: 11, reorderLevel: 5, tags: ["Accessory", "Upsell", "Retail"], notes: "Popular reception upsell with winter service jobs.", lastUsedDate: "2026-04-18" },
  { id: "PART-007", category: "Electrical", sourceType: "Aftermarket", partNumber: "LN5-096", alternatePartNumber: "BAT-096-AGM", name: "AGM battery 096", vehicleCompatibility: ["BMW 320d", "Mercedes-Benz Vito 116 CDI"], supplierId: "SUP-003", supplierSku: "GA-BAT-096", unitPrice: 2460, retailPrice: 2990, stockOnHand: 1, reorderLevel: 2, tags: ["Battery", "Electrical", "Common failure"], notes: "Preferred fit for start-stop replacements with coding note attached.", lastUsedDate: "2026-04-12" },
];

export const huttonPartRequests: HuttonPartRequest[] = [
  { id: "PO-401", jobId: "HM-24020", partId: "PART-001", quantity: 1, status: "Ordered", requestedBy: "Jaco Louw", urgency: "Priority", eta: "Today 15:30", supplierId: "SUP-002", notes: "Client approved on WhatsApp at 09:26." },
  { id: "PO-402", jobId: "HM-24018", partId: "PART-003", quantity: 1, status: "Backordered", requestedBy: "Mia Kleyn", urgency: "Urgent", eta: "Tomorrow 10:00", supplierId: "SUP-003", notes: "Hold bay time until part lands." },
  { id: "PO-403", jobId: "HM-24016", partId: "PART-005", quantity: 1, status: "Arrived", requestedBy: "Sipho Mthembu", urgency: "Routine", eta: "Arrived 08:05", supplierId: "SUP-001", notes: "Ready for fitment and road test." },
];

export const huttonTransportTasks: HuttonTransportTask[] = [
  { id: "TR-220", jobId: "HM-24020", clientId: "CL-001", tripType: "Return", driver: "Wayne Petersen", vehicle: "Hutton Shuttle 1", pickupFrom: "Hutton Motors Reception", dropoffTo: "Century City Office Park", requestedTime: "Today 16:45", status: "Return Trip Pending", notes: "Client needs drop-off before school-run traffic builds." },
  { id: "TR-221", jobId: "HM-24023", clientId: "CL-003", tripType: "Pickup", driver: "Lebo Maseko", vehicle: "Hutton Shuttle 2", pickupFrom: "Green Point Apartment", dropoffTo: "Hutton Motors Reception", requestedTime: "Today 13:00", status: "Driver Assigned", notes: "Urgent afternoon pickup for diagnostics booking." },
  { id: "TR-222", jobId: "HM-24018", clientId: "CL-006", tripType: "Drop-off", driver: "Wayne Petersen", vehicle: "Hutton Shuttle 1", pickupFrom: "Hutton Motors Reception", dropoffTo: "Foreshore Client Office", requestedTime: "Today 17:15", status: "Requested", notes: "Return drop once job moves to ready." },
  { id: "TR-223", jobId: "HM-24014", clientId: "CL-002", tripType: "Pickup", driver: "Unassigned", vehicle: "Shuttle pool", pickupFrom: "Paarden Eiland Fleet Depot", dropoffTo: "Hutton Motors Reception", requestedTime: "Today 14:15", status: "Scheduled", notes: "Fleet driver requested assisted collection after invoice sign-off." },
];

export const huttonJobs: HuttonJob[] = [
  { id: "HM-24018", clientId: "CL-006", vehicleId: "VH-006", advisor: "Lerato Adams", technicianId: "TECH-002", status: "Waiting for Parts", bookingStatus: "Completed", priority: "Urgent", bookingTime: "Today 07:45", promisedTime: "Tomorrow 16:00", etaLabel: "ETA tomorrow 16:00", concern: "Engine light on, reduced power, long-distance shuttle vehicle.", estimate: 8950, approvedAmount: 8950, progressPercent: 58, bay: "Bay 3", checklist: ["Scan complete", "Fault report sent", "Client approved replacement sensor"], recommendedWork: ["NOx sensor replacement", "Software adaptation", "Road test"], bookingNotes: "Client asked for earliest possible turnaround because the van is tied to shuttle routes.", pickupAddress: "Foreshore business district", dropoffAddress: "Foreshore business district", vehicleCondition: "Minor stone chips on bonnet, no visible interior damage, fuel at quarter tank.", clientComplaint: "Loss of power under load with engine light active.", photoChecklist: ["Front three-quarter photo captured", "Odometer photo captured", "Existing rear bumper scuff recorded"], queueStatus: "Waiting on supplier ETA", technicianNotes: "NOx sensor fault confirmed. Vehicle should not be heavily loaded until replacement is fitted.", inspectionFindings: "Stored emissions faults and reduced-power mode triggered after highway run.", approvalSummary: "Approved in full by Brandon via WhatsApp at 10:18.", approvalNotes: "Client requested ETA update the moment the part is confirmed.", transportRequired: true, transportTaskId: "TR-222", partRequestIds: ["PO-402"], alerts: ["Vehicle tied to airport shuttle bookings", "Part ETA impacts promised time"], whatsappStatus: "Attention Needed", internalNotes: "Escalate to workshop manager if supplier slips beyond 10:00 tomorrow.", nextStep: "Receive sensor and complete adaptation." },
  { id: "HM-24020", clientId: "CL-001", vehicleId: "VH-001", advisor: "Zanele Mokoena", technicianId: "TECH-001", status: "In Service", bookingStatus: "Completed", priority: "High", bookingTime: "Today 08:10", promisedTime: "Today 17:00", etaLabel: "ETA today 17:00", concern: "72-point service, brake vibration, request same-day completion.", estimate: 6240, approvedAmount: 6240, progressPercent: 76, bay: "Bay 1", checklist: ["Vehicle collected", "Brake skim approved", "Service checklist underway"], recommendedWork: ["Minor service", "Front brake pad replacement", "Wheel balance"], bookingNotes: "Client needs collection before the school run and asked for a proactive update by 16:00.", pickupAddress: "Century City Office Park", dropoffAddress: "Century City Office Park", vehicleCondition: "Vehicle clean overall, front tyres at 4 mm, light scratch on left rear door already noted.", clientComplaint: "Brake vibration at highway speed and due for scheduled service.", photoChecklist: ["Odometer photo captured", "Front tyre condition photo captured"], queueStatus: "In bay with senior technician", technicianNotes: "Brake skim completed. Final road test after pad bedding still outstanding.", inspectionFindings: "Front pads worn to 3 mm and light disc runout confirmed.", approvalSummary: "Reception got full approval before 09:30.", approvalNotes: "Same-day authorization confirmed without additional quote delay.", transportRequired: true, transportTaskId: "TR-220", partRequestIds: ["PO-401"], alerts: ["Collection promised before aftercare school run"], whatsappStatus: "Client Replied", internalNotes: "Reception to confirm shuttle return slot when QC starts.", nextStep: "Finish brake work and move to quality check." },
  { id: "HM-24021", clientId: "CL-004", vehicleId: "VH-004", advisor: "Lerato Adams", technicianId: "TECH-002", status: "Waiting for Approval", bookingStatus: "Completed", priority: "High", bookingTime: "Today 09:20", promisedTime: "Tomorrow 12:00", etaLabel: "Awaiting approval", concern: "Rear suspension noise and service indicator reset.", estimate: 11800, approvedAmount: null, progressPercent: 34, bay: "Bay 4", checklist: ["Initial inspection complete", "Video sent to client", "Quote awaiting response"], recommendedWork: ["Rear control arm bush kit", "Brake fluid service", "Wheel alignment"], bookingNotes: "Client asked reception not to proceed on any extras without a direct call first.", vehicleCondition: "Vehicle presents well with no fresh body damage, rear tyres slightly unevenly worn.", clientComplaint: "Knocking noise from rear over speed bumps and warning for service reset.", photoChecklist: ["Rear suspension video recorded", "Tyre wear photo captured"], queueStatus: "Held in approval bay", technicianNotes: "Noise trace points to rear control arm bush wear. Safe to move but not ideal to delay too long.", inspectionFindings: "Rear suspension bush wear confirmed, brake fluid moisture elevated.", approvalSummary: "Video estimate sent at 11:05, waiting for client confirmation.", approvalNotes: "Needs advisor phone call before job can be released.", transportRequired: false, partRequestIds: [], alerts: ["Client asked for call before any additional work"], whatsappStatus: "Awaiting Reply", internalNotes: "If approval lands after 15:00, rebook alignment slot for tomorrow morning.", nextStep: "Get approval and release parts request." },
  { id: "HM-24016", clientId: "CL-005", vehicleId: "VH-005", advisor: "Zanele Mokoena", technicianId: "TECH-003", status: "Quality Check", bookingStatus: "Completed", priority: "Normal", bookingTime: "Today 07:15", promisedTime: "Today 15:30", etaLabel: "ETA today 15:30", concern: "Annual service and cabin vibration at idle.", estimate: 3840, approvedAmount: 3840, progressPercent: 92, bay: "Bay 5", checklist: ["Service complete", "Air filter replaced", "Road test done"], recommendedWork: ["Annual service", "Air filter replacement", "Idle relearn"], bookingNotes: "Routine annual service with request to check idle vibration before handover.", vehicleCondition: "Good overall condition, no new external defects noted, fuel half tank.", clientComplaint: "Slight cabin vibration at idle after morning start.", photoChecklist: ["Odometer photo captured"], queueStatus: "Awaiting final QC sign-off", technicianNotes: "Idle relearn completed and vibration improved after service items were reset.", inspectionFindings: "Air filter restricted and throttle body adaptation required.", approvalSummary: "All work approved at booking intake.", approvalNotes: "No further approvals required.", transportRequired: false, partRequestIds: ["PO-403"], alerts: ["Ready for wash and final QC sign-off"], whatsappStatus: "Synced", internalNotes: "Send collection message once wash lane clears.", nextStep: "Final QC and collection message." },
  { id: "HM-24023", clientId: "CL-003", vehicleId: "VH-003", advisor: "Aimee Roberts", technicianId: "TECH-004", status: "Booking Confirmed", bookingStatus: "Confirmed", priority: "Normal", bookingTime: "Today 13:30", promisedTime: "Tomorrow 11:00", etaLabel: "Pickup today 13:00", concern: "Warning light after long trip, client asked for pickup from office.", estimate: 1650, approvedAmount: null, progressPercent: 10, bay: "Awaiting arrival", checklist: ["Booking confirmed", "Shuttle arranged", "Reception notes loaded"], recommendedWork: ["Diagnostic scan", "Battery test", "Check software campaigns"], bookingNotes: "Shuttle collection requested from office before 13:00 if possible.", pickupAddress: "Green Point Apartment", dropoffAddress: "Green Point Apartment", vehicleCondition: "To be captured at check-in.", clientComplaint: "Warning light appeared after a long-distance drive.", photoChecklist: ["Photo capture pending at arrival"], queueStatus: "Booked into reception lane", technicianNotes: "Awaiting vehicle arrival.", inspectionFindings: "Inspection not started yet.", approvalSummary: "Inspection estimate to be confirmed after scan.", approvalNotes: "No approval notes yet.", transportRequired: true, transportTaskId: "TR-221", partRequestIds: [], alerts: ["Pickup must be on time for office handover"], whatsappStatus: "Client Replied", internalNotes: "Reception to call if pickup slips by more than 15 minutes.", nextStep: "Collect vehicle and complete intake." },
  { id: "HM-24014", clientId: "CL-002", vehicleId: "VH-002", advisor: "Aimee Roberts", technicianId: "TECH-001", status: "Ready for Collection", bookingStatus: "Completed", priority: "High", bookingTime: "Yesterday 14:45", promisedTime: "Today 14:00", etaLabel: "Ready now", concern: "100,000 km service and brake inspection for fleet usage.", estimate: 7420, approvedAmount: 7420, progressPercent: 100, bay: "Valet Lane", checklist: ["Service complete", "Road test complete", "Invoice prepared"], recommendedWork: ["Major service", "Brake fluid flush", "Wiper blade upsell"], bookingNotes: "Fleet collection driver to collect after lunch window.", vehicleCondition: "Fleet-use wear consistent with age, no new damage at check-in.", clientComplaint: "Scheduled 100,000 km service with brake inspection request.", photoChecklist: ["Check-in photo pack complete"], queueStatus: "Ready at reception", technicianNotes: "Work completed and road-tested. Brake feel normal after flush.", inspectionFindings: "Pads acceptable, brake fluid degraded, service items due.", approvalSummary: "Fleet manager approved via email and phone.", approvalNotes: "Fleet line item approved under standard account.", transportRequired: false, partRequestIds: [], alerts: ["Waiting on fleet collection driver"], whatsappStatus: "Synced", internalNotes: "Close immediately after signature and document upload.", nextStep: "Handover pack and close on collection." },
];

export const huttonCalendarEvents: HuttonCalendarEvent[] = [
  { id: "CAL-001", title: "Fortuner service booking", clientName: "Sarah Daniels", phoneNumber: "082 443 1902", vehicleLabel: "Toyota Fortuner 2.8 GD-6", registration: "CA 598-214", linkedRecordId: "HM-24020", jobId: "HM-24020", clientId: "CL-001", eventType: "Booking", startAt: "2026-04-23T08:00:00+02:00", endAt: "2026-04-23T08:30:00+02:00", status: "Confirmed", assignedStaff: "Zanele Mokoena", notes: "Same-day service booking with brake vibration concern and proactive update promised before 16:00.", address: "Century City Office Park", source: "Seeded" },
  { id: "CAL-002", title: "Office pickup request", clientName: "Sarah Daniels", phoneNumber: "082 443 1902", vehicleLabel: "Toyota Fortuner 2.8 GD-6", registration: "CA 598-214", linkedRecordId: "TR-220", jobId: "HM-24020", clientId: "CL-001", eventType: "Vehicle Pickup", startAt: "2026-04-23T08:15:00+02:00", endAt: "2026-04-23T08:45:00+02:00", status: "Completed", assignedStaff: "Wayne Petersen", notes: "Morning shuttle completed from office to reception before technician handover.", address: "Century City Office Park", source: "Seeded" },
  { id: "CAL-003", title: "Approval follow-up call", clientName: "Ahmed Patel", phoneNumber: "072 618 4500", vehicleLabel: "BMW 320d M Sport", registration: "CF 110-335", linkedRecordId: "HM-24021", jobId: "HM-24021", clientId: "CL-004", eventType: "Approval Follow-up", startAt: "2026-04-23T10:30:00+02:00", endAt: "2026-04-23T10:45:00+02:00", status: "Awaiting Response", assignedStaff: "Lerato Adams", notes: "Client asked for a direct call before extra suspension work is authorised.", source: "Seeded" },
  { id: "CAL-004", title: "Ready for collection reminder", clientName: "Musa Khumalo", phoneNumber: "071 228 4411", vehicleLabel: "Ford Ranger 2.0 Bi-Turbo XLT", registration: "CY 883-771", linkedRecordId: "HM-24014", jobId: "HM-24014", clientId: "CL-002", eventType: "Vehicle Collection", startAt: "2026-04-23T15:00:00+02:00", endAt: "2026-04-23T15:15:00+02:00", status: "Scheduled", assignedStaff: "Aimee Roberts", notes: "Fleet driver collection moved to later afternoon. Reception to reconfirm handover window.", source: "Seeded" },
  { id: "CAL-005", title: "Next service follow-up", clientName: "Nomsa Dlamini", phoneNumber: "084 511 3782", vehicleLabel: "Hyundai Tucson 2.0 Executive", registration: "CAA 443-10", linkedRecordId: "HM-24016", jobId: "HM-24016", clientId: "CL-005", eventType: "Follow-up", startAt: "2026-04-30T09:30:00+02:00", endAt: "2026-04-30T09:45:00+02:00", status: "Scheduled", assignedStaff: "Zanele Mokoena", notes: "Post-service check-in and next-service reminder one week after handover.", source: "Seeded" },
  { id: "CAL-006", title: "Workshop parts ETA reminder", clientName: "Brandon Louw", phoneNumber: "079 998 4422", vehicleLabel: "Mercedes-Benz Vito 116 CDI Tourer", registration: "CAW 905-77", linkedRecordId: "HM-24018", jobId: "HM-24018", clientId: "CL-006", eventType: "Internal Workshop Reminder", startAt: "2026-04-23T12:30:00+02:00", endAt: "2026-04-23T12:45:00+02:00", status: "Pending", assignedStaff: "Workshop Manager", notes: "Escalate supplier by lunchtime if the NOx sensor ETA is still not firm.", source: "Seeded" },
];

export const huttonInbox: HuttonInboxMessage[] = [
  { id: "IN-708", clientId: "CL-007", receivedAt: "07:36", subject: "Need to book my Ranger tomorrow morning", preview: "Hi I need to book my Ford Ranger for a service tomorrow morning. My reg is CY 998-221. Jason here.", classification: "Booking Query", routedTo: "Reception", urgent: false, priority: "Priority", status: "New", suggestedReply: "Your booking with Hutton Motors has been scheduled for tomorrow at 08:00. Reply here if you need to change anything.", humanAttentionRequired: false, aiBookingAnalysis: { detectedIntent: true, confidence: 0.94, extractedFields: { customerName: "Jason Naidoo", phoneNumber: "082 650 1184", vehicleMake: "Ford", vehicleModel: "Ranger", registration: "CY 998-221", serviceRequest: "Routine service", preferredDate: "Tomorrow", preferredTime: "08:00", urgency: "Normal" }, missingCoreFields: [], reasoning: "The message includes customer identity, contact number, vehicle description, requested work, date, and a clear morning slot.", automationApplied: false } },
  { id: "IN-709", clientId: "CL-008", receivedAt: "08:02", subject: "Can you fit my Polo in on Friday?", preview: "Can you fit my Polo in on Friday? It needs a service. Chantel.", classification: "Booking Query", routedTo: "Reception", urgent: false, priority: "Normal", status: "New", suggestedReply: "Thanks, we can help with that. Please send your vehicle model and preferred time so we can confirm your booking.", humanAttentionRequired: false, aiBookingAnalysis: { detectedIntent: true, confidence: 0.81, extractedFields: { customerName: "Chantel Meyer", phoneNumber: "083 332 9914", vehicleMake: "Volkswagen", vehicleModel: "Polo", serviceRequest: "Service", preferredDate: "Friday" }, missingCoreFields: ["Preferred time"], reasoning: "The booking intent and vehicle are clear, but a usable time preference is still missing.", automationApplied: false } },
  { id: "IN-710", clientId: "CL-009", receivedAt: "08:27", subject: "Hilux brakes and lift home", preview: "My Hilux needs brakes and I need a lift home from 14 Durham Road, Rondebosch. Can you book me for next week Tuesday at 09:00?", classification: "Transport Request", routedTo: "Reception", urgent: true, priority: "Urgent", status: "Assigned", suggestedReply: "Your booking with Hutton Motors has been scheduled for next Tuesday at 09:00. We have also flagged your transport request for the shuttle coordinator.", humanAttentionRequired: false, aiBookingAnalysis: { detectedIntent: true, confidence: 0.91, extractedFields: { customerName: "Sibusiso Mokoena", phoneNumber: "071 904 7782", vehicleMake: "Toyota", vehicleModel: "Hilux", serviceRequest: "Brake inspection and repair", preferredDate: "Next Tuesday", preferredTime: "09:00", transportRequired: true, pickupAddress: "14 Durham Road, Rondebosch", urgency: "Urgent" }, missingCoreFields: [], reasoning: "The message includes a clear date, time, service request, and transport need, so it can be booked if a slot is open.", automationApplied: false } },
  { id: "IN-711", clientId: "CL-010", receivedAt: "08:41", subject: "Major service for Monday", preview: "Can I book a major service for Monday at 08:00 for my BMW 320d? Priya here.", classification: "Booking Query", routedTo: "Reception", urgent: false, priority: "Priority", status: "New", suggestedReply: "We are full at 08:00 on Monday. We do have 10:30 or 13:00 available if one of those works for you.", humanAttentionRequired: false, aiBookingAnalysis: { detectedIntent: true, confidence: 0.9, extractedFields: { customerName: "Priya Govender", phoneNumber: "084 219 6670", vehicleMake: "BMW", vehicleModel: "320d", serviceRequest: "Major service", preferredDate: "Monday", preferredTime: "08:00", urgency: "Normal" }, missingCoreFields: [], reasoning: "The booking request is complete, but the requested slot needs to be checked against current capacity.", alternativeSlots: ["Monday 10:30", "Monday 13:00"], automationApplied: false } },
  { id: "IN-712", clientId: "CL-011", receivedAt: "09:05", subject: "Want to bring my car in next week", preview: "I want to bring my car in next week. Can someone advise what you need from me?", classification: "Booking Query", routedTo: "Reception", urgent: false, priority: "Normal", status: "New", suggestedReply: "Thanks, we can help with that. Please send your vehicle make and model, what needs attention, and the day or time that suits you best.", humanAttentionRequired: true, aiBookingAnalysis: { detectedIntent: true, confidence: 0.58, extractedFields: { customerName: "Megan Jacobs", phoneNumber: "082 119 3408", preferredDate: "Next week" }, missingCoreFields: ["Vehicle description", "Service request", "Preferred time"], reasoning: "There is clear booking intent, but the vehicle, issue, and timing details are still too vague to draft a reliable booking.", automationApplied: false } },
  { id: "IN-701", clientId: "CL-006", jobId: "HM-24018", receivedAt: "11:18", subject: "Part ETA?", preview: "Please confirm whether the sensor will arrive today because we need the shuttle van back tomorrow morning.", classification: "Urgent Issue", routedTo: "Parts / Admin", urgent: true, priority: "Urgent", status: "Assigned", suggestedReply: "We have escalated the sensor ETA with the supplier and will update you by 12:30 with a confirmed arrival window.", humanAttentionRequired: true },
  { id: "IN-702", clientId: "CL-004", jobId: "HM-24021", receivedAt: "11:42", subject: "Please call before proceeding", preview: "I saw the video. Please phone me before doing the control arm work.", classification: "Quote Rejection", routedTo: "Workshop Manager", urgent: false, priority: "Priority", status: "New", suggestedReply: "We will call you before authorising any additional work and keep the vehicle on hold until we speak.", humanAttentionRequired: true },
  { id: "IN-703", clientId: "CL-003", jobId: "HM-24023", receivedAt: "12:03", subject: "Can your shuttle collect me earlier?", preview: "I may need to leave the office by 12:30 if possible.", classification: "Transport Request", routedTo: "Shuttle Coordinator", urgent: false, priority: "Priority", status: "New", suggestedReply: "We are checking the shuttle route now and will confirm whether we can move your pickup earlier.", humanAttentionRequired: false },
  { id: "IN-704", clientId: "CL-001", jobId: "HM-24020", receivedAt: "12:24", subject: "Will it be done before 5?", preview: "Please keep me posted. I need to fetch the kids after work.", classification: "Progress Request", routedTo: "Reception", urgent: false, priority: "Normal", status: "Handled", suggestedReply: "Your Fortuner is still on track and we will send a firm completion update before 16:00.", humanAttentionRequired: false },
  { id: "IN-705", clientId: "CL-005", jobId: "HM-24016", receivedAt: "09:10", subject: "Can you send the invoice?", preview: "Please email the invoice and final amount before I leave the office.", classification: "Invoice Question", routedTo: "Reception", urgent: false, priority: "Normal", status: "Handled", suggestedReply: "We will send the invoice and final handover amount to your email within the next few minutes.", humanAttentionRequired: false },
  { id: "IN-706", clientId: "CL-002", jobId: "HM-24014", receivedAt: "13:08", subject: "Need to move collection to 15:30", preview: "Our fleet driver is running late. Can collection move to half past three?", classification: "Reschedule Request", routedTo: "Reception", urgent: false, priority: "Normal", status: "Assigned", suggestedReply: "No problem. We have moved your collection slot to 15:30 and the vehicle will remain ready at reception.", humanAttentionRequired: false },
  { id: "IN-707", clientId: "CL-001", jobId: "HM-24020", receivedAt: "13:14", subject: "Approve brake work", preview: "Approved. Please go ahead with the pads and service items.", classification: "Quote Approval", routedTo: "Workshop Manager", urgent: false, priority: "Priority", status: "Handled", suggestedReply: "Thank you, we have released the approved brake work and service items to the workshop.", humanAttentionRequired: false },
];

export const huttonWhatsAppTimeline: Record<string, HuttonWhatsAppUpdate[]> = {
  "HM-24018": [
    { id: "WA-801", at: "08:14", direction: "Outgoing", sender: "Hutton Service Updates", message: "Your Vito has been checked in. Diagnostics are underway in Bay 3.", tone: "Neutral" },
    { id: "WA-802", at: "10:18", direction: "Incoming", sender: "Brandon Louw", classification: "Quote Approval", routedTo: "Workshop Manager", message: "Approved. Please order the NOx sensor and keep me posted on ETA.", tone: "Neutral" },
    { id: "WA-803", at: "11:18", direction: "Incoming", sender: "Brandon Louw", classification: "Urgent Issue", routedTo: "Parts / Admin", message: "Please confirm if the van can be ready for morning shuttle work tomorrow.", tone: "Concerned" },
  ],
  "HM-24020": [
    { id: "WA-804", at: "08:32", direction: "Outgoing", sender: "Hutton Service Updates", message: "Your Fortuner has arrived and the shuttle drop-off is complete.", tone: "Positive" },
    { id: "WA-805", at: "09:26", direction: "Outgoing", sender: "Zanele Mokoena", message: "Brake skim and pad replacement approved. Service work is now in progress.", tone: "Neutral" },
    { id: "WA-806", at: "12:24", direction: "Incoming", sender: "Sarah Daniels", classification: "Progress Request", routedTo: "Reception", message: "Please keep me posted before 4pm so I can plan collection.", tone: "Neutral" },
  ],
  "HM-24021": [
    { id: "WA-807", at: "11:05", direction: "Outgoing", sender: "Lerato Adams", message: "Inspection complete. We found rear suspension wear and sent your quote video.", tone: "Neutral" },
    { id: "WA-808", at: "11:42", direction: "Incoming", sender: "Ahmed Patel", classification: "Quote Rejection", routedTo: "Workshop Manager", message: "Please call me first before doing the extra work.", tone: "Concerned" },
  ],
  "HM-24016": [
    { id: "WA-809", at: "08:22", direction: "Outgoing", sender: "Hutton Service Updates", message: "Your Tucson is in quality check. We are on track for collection this afternoon.", tone: "Positive" },
  ],
  "HM-24023": [
    { id: "WA-810", at: "12:03", direction: "Incoming", sender: "Lynette Fourie", classification: "Transport Request", routedTo: "Shuttle Coordinator", message: "Can the shuttle collect me a bit earlier if possible?", tone: "Neutral" },
  ],
  "HM-24014": [
    { id: "WA-811", at: "09:04", direction: "Outgoing", sender: "Aimee Roberts", message: "Your Ranger is ready for collection. Invoice and inspection report are attached.", tone: "Positive" },
  ],
};

export const huttonServiceData: HuttonServiceDataset = {
  clients: huttonClients,
  vehicles: huttonVehicles,
  technicians: huttonTechnicians,
  suppliers: huttonSuppliers,
  parts: huttonParts,
  partRequests: huttonPartRequests,
  jobs: huttonJobs,
  transportTasks: huttonTransportTasks,
  inbox: huttonInbox,
  whatsappByJob: huttonWhatsAppTimeline,
  calendarEvents: huttonCalendarEvents,
};
